name: Terraform AWS CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
  

permissions:
  id-token: write  # Needed for OIDC
  contents: read

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::796973493759:role/gha-role
          role-session-name: GitHubActionsTerraform
          aws-region: ap-south-1  # Change to your AWS region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infra

      # - name: Terraform Format Check
      #   run: terraform fmt -check
      #   working-directory: ./infra

      # - name: Terraform Validate
      #   run: terraform validate
      #   working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infra

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
        if: github.event_name == 'pull_request'

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve
      #   working-directory: ./infra
